### ISSUE TITLE
ats_2 size on arm devices

### ISSUE THREAD

**Issue by ArianK16a** [sonyxperiadev/timekeep#23]
/data/vendor/time/ats_2 should store the time offset as uint64_t, that means the file size should be 8 bytes as far as i know. This is also the case when using the proprietary time_daemon from the stock OS. However on my aries (shinano family, also confirmed the same on rhine) the file size is pretty much always 4 bytes. That leads TWRP to not being able to read it. It complains about it: "I: TWFunc::Fixup_Time: failed to load uint64 from file /data/vendor/time/ats_2" Even though sometimes (i didn't find a way to reproduce it) the size is 8 bytes though and then TWRP can read the file just fine.
Thats what i observed. I don't really understand c but from what i see, the offset is stored as unsigned long in timekeep.c and if i recall correctly the length of that is dependent on the architecture, so on our arm it is 4 byte and on arm64 it is 8 byte. I think it should always be 8 byte, like the file has when it's created by time_daemon.
I don't know where i can start to ensure timekeep writes the file as 8 byte size. Can someone help us?

**Comment by MarijnS95** [comment]
Indeed, the `unsigned long` used in the code (`restore_ats`) is only 4 bytes on 32-bit architectures.

I'll fix this by using a proper `uint64_t` type.

**Comment by ArianK16a** [comment]
Thank you. Problem is fixed with the PR.
